# Generated by Django 6.0.5 on 2026-05-22 10:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='CollegeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='College latitude (decimal degrees)')),
                ('longitude', models.FloatField(help_text='College longitude (decimal degrees)')),
                ('radius_meters', models.IntegerField(default=100, help_text='Permitted radius in meters within which attendance can be marked')),
                ('college_name', models.CharField(blank=True, default='My College', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College Configuration',
                'verbose_name_plural': 'College Configuration',
            },
        ),
    ]
