# Generated by Django 6.0.5 on 2026-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_subject_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='scanned_lat',
            field=models.FloatField(blank=True, help_text='Latitude captured during scan', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scanned_long',
            field=models.FloatField(blank=True, help_text='Longitude captured during scan', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='qr_secret_seed',
            field=models.CharField(blank=True, help_text='Secret seed for generating rotating QR codes', max_length=64),
        ),
    ]
